name: integration-tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_PIA_BACK_URL: ${{ secrets.CYPRESS_PIA_BACK_URL }}
          CYPRESS_PIA_BACK_ID: ${{ secrets.CYPRESS_PIA_BACK_ID }}
          CYPRESS_PIA_BACK_SECRET: ${{ secrets.CYPRESS_PIA_BACK_SECRET }}
        with:
          start: yarn start
          browser: chrome
          headless: true
          wait-on: http://localhost:4200
